services:
  - type: web
    name: makasete-calo-gohan
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bin/rails server -p $PORT -e production"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false